##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
pipeline:
  - docker
  - helm
#  - zip
zipGlobs:
  - target/*.jar
  - conf/**
excludeGlobs:
  - Dockerfile
  - .helmignore
  - .dockerignore
  - .git*
  - .git/
  - OWNER*
  - README.md
  - jenkins*
  - charts/
  - cloudopsworks-ci
  - skafold*
  - original-*.jar
# cd:
#   env: dev