##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Static Analysis Process
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true
      sonarqubeUrl:
        required: true
      sonarqubeToken:
        required: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ inputs.ref }}
      # Setup Java JDK for builds
      - name: Set JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "zulu"

      # Cache all maven packages
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the code!
      - name: Static Test Code
        env:
          JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms128m -Xmx2048m"
          SONARQUBE_URL: ${{ secrets.sonarqubeUrl }}
          SONARQUBE_TOKEN: ${{ secrets.sonarqubeToken }}
        run: |
          mvn --batch-mode test
          mvn --batch-mode sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN
